### ISSUE TITLE
Tests depend on the exact order of the pkg-config output

### ISSUE THREAD

**Issue by terceiro** [ruby-gnome2/pkg-config#6]
At least on my system, pkg-config and /usr/bin/pkg-config generate the flags in a different order, and that makes some tests fail:

```
$ rake
(in /home/terceiro/src/debian/pkg-ruby-extras/ruby-pkg-config)
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2011-10-01.
Gem::Specification#has_rdoc= called from /usr/lib/ruby/vendor_ruby/hoe.rb:454
.
/usr/bin/ruby1.8 -w -Ilib:bin:test:. -e 'require "rubygems"; require "test/unit"; require "test/test_pkg_config.rb"' -- 
Loaded suite -e
Started
FF.........
Finished in 0.2802 seconds.

  1) Failure:
test_cflags(PkgConfigTest)
    [./test/test_pkg_config.rb:112:in `assert_pkg_config'
     ./test/test_pkg_config.rb:20:in `test_cflags']:
<"-pthread -I/usr/include/freetype2 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/tmp/local/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12"> expected but was
<"-pthread -I/usr/include/cairo -I/usr/include/glib-2.0 -I/tmp/local/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12">.

  2) Failure:
test_cflags_only_I(PkgConfigTest)
    [./test/test_pkg_config.rb:112:in `assert_pkg_config'
     ./test/test_pkg_config.rb:25:in `test_cflags_only_I']:
<"-I/usr/include/freetype2 -I/usr/include/cairo -I/usr/include/glib-2.0 -I/tmp/local/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/libpng12"> expected but was
<"-I/usr/include/cairo -I/usr/include/glib-2.0 -I/tmp/local/lib/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12">.

11 tests, 26 assertions, 2 failures, 0 errors
rake aborted!
Command failed with status (1): [/usr/bin/ruby1.8 -w -Ilib:bin:test:. -e 'r...]

(See full trace by running task with --trace)
```

I suggest to just ignore the order, like this:

http://anonscm.debian.org/gitweb/?p=pkg-ruby-extras/ruby-pkg-config.git;a=commitdiff;h=6d16d2fa7adad6d51d84f52377df29b9c51ae657

**Comment by dai-vdr** [comment]
this bug was revived...:

* https://bugs.debian.org/895923
* https://bugs.debian.org/896074

**Comment by kou** [comment]
Thanks. I've fixed and released a new version.

I hope that you open a new issue instead of reusing existing issue.

**Comment by dai-vdr** [comment]
I see but this issue has been open for a long time (i did not reopen it).
Are there any reasons to keep it open, or could you please close it?

**Comment by kou** [comment]
Ah, I see.
This should be closed.
